### ISSUE TITLE
Rosaria.png asset does not exist

### ISSUE THREAD

**Issue by Wollus** [Unknown008/genshin-mats#24]
See title.

**Comment by Unknown008** [comment]
Thank you, I forgot to add the file. Should be good now

**Comment by Wollus** [comment]
Wow, that response time, haha. I'm impressed. Thanks!!

For me to be able to help out in the future, where do you get the .png assets from?

**Comment by Unknown008** [comment]
Lol, I happened to be free right now (eating dinner), I usually get them from the wiki [here](https://genshin-impact.fandom.com/wiki/Characters) and upsize it if it was shrunk (you can see it from the url of the picture)

Cheers!
